## A quick introduction to Python for Astronomers

Developted for Practical Introduction to Research Class at UT Austin

Emma Yu, Fall 2015 

### 1. Backgroud

After a few weeks of experence with IDL, many of you are already IDL ninjas. Now let's have a look at a new language in which a lot of Astronomical packages are now available - [Python](https://www.python.org/).

Python is an object-orientied, dynamic, general-purpose language. Unlike C and Fortran, it's a [interpreted language](https://en.wikipedia.org/wiki/Interpreted_language), which means the code is interpreted at runtime, and one does not need to compile the code ahead of time. Python is an free and [open source software](https://en.wikipedia.org/wiki/Free_and_open-source_software), which means one does not need to pay anything to use it, and everyone welcome to contribute and make the software better! 

The language was first develoted by Guido van Rossum, and the first version appearred in 1991. There are a few popular distributions available for easy installation and package management. I personally recomend [Anoconda](https://store.continuum.io/cshop/anaconda/), which has made my life much easier.   

This tutorial is written in Jupyter notebook included in [iPython](http://ipython.org/), which is a package built upon python that allows me to write program in a browser, and save all the instructions, code, and plots in one place. It's great for writing a proposal like this, but may not be optimal for writing a large project. 

### 2. A few differences between Python and IDL

#### Similarities:
- index starts from 0.
- the data type is dynamic - it can be changed in the code.
- Note that "copy" only generates a new view and does not actually copy the data!!!!

#### Differences:

- Python uses indentation to denote the structure of the code. 
- Things are organized as objects in Python.
- The basic Python does not support what we want to do. One needs to load several packages for example to manipulate multi-dimensional arrays.



### 3. Array basics

For our purpose, we will mostly use the Numpy package to manipulate array-based data.

First, let load the package by:

In [1]:
import numpy as np

Numpy supports array data type just as the array we've previously seen in IDL. Similar to 'findgen', one can generate an array with indics by: 

In [3]:
a = np.arange(15)
print a

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


One can tell the propertis of the array and apply procedures to the array by using "arrayname dot nameoftheprocedure". 

In [5]:
# For example, to rearrange it
a = a.reshape(3,5)
print a

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [6]:
# To find out the shape
a.shape

(3, 5)

In [7]:
# To find out the type of data contained in the array
a.dtype.name


'int64'

As we've seen in the code example, "#" denotes comments in Python, and the line afte the # sign will not be executed.

One can also create arrays by specifying the elements. 

In [8]:
b = np.array([[4,6,2,6],[5,7,2,8]])
print b

[[4 6 2 6]
 [5 7 2 8]]


Similar to IDL, a function to the array can be broadcasted to every element, so unlike C and Fortran, one doesn't have to loop through every element. 

In [9]:
print b*2

[[ 8 12  4 12]
 [10 14  4 16]]


In [10]:
print b**2

[[16 36  4 36]
 [25 49  4 64]]


To slice the array or access individual elements, one can select by location just as in IDL, and the index start from 0 as well.

In [11]:
print b[0,0:2]

[4 6]


":" means everything, just like "*" in IDL.

In [14]:
print b[0,:]

[4 6 2 6]


### 4. Control Structure

### 5. User defined functions

### 6. Plotting

In [15]:
# line plot, scatter plot, histogram, 2D maps